
name: whisper_connect_hub
description: "A sleek Flutter chat application with real-time messaging, customizable profiles, and intuitive UI for seamless communication."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  provider: ^6.0.5 # Added for state management
  shared_preferences: ^2.2.3 # Added for local settings
  hive: ^2.0.4 # Added for offline message storage
  hive_flutter: ^1.1.0 # Added for Flutter integration with Hive
  path_provider: ^2.1.3 # Added for getting application document directory for Hive

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1 # For generating Hive adapters
  build_runner: ^2.4.9 # For running code generators

flutter:
  uses-material-design: true
